#!/bin/bash
##----------LICENSE NOTICE-------------------------------------------------------------------------------------------------------##
##  This file is part of GBTelera: A Gameboy Development Framework                                                               ##
##  Copyright (C) 2024 Francisco J. Gallego-Durán (aka. ronaldo / Cheesetea/ByteRealms) (@FranGallegoBR)                         ##
##                                                                                                                               ##
## Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation    ##
## files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy,    ##
## modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the         ##
## Softwareis furnished to do so, subject to the following conditions:                                                           ##
##                                                                                                                               ##
## The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.##
##                                                                                                                               ##
## THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE          ##
## WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR         ##
## COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,   ##
## ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                         ##
##-------------------------------------------------------------------------------------------------------------------------------##

##
## File: gbt_mkproject
##    This script helps in the creation of new projects that use GBTelera framework.
##
## Usage:
##    <gbt_mkproject> [foldername] [options]
##
## Description:
##    This script creates a new folder and fills it up with required files to use that folder as a basic GBTelera project. 
## Once the folder is created, you only have to launch 'make' command inside it to build the project an generate the GB file. 
## A basic main.asm and header.asm source files are created under src/ sub-folder, and a standard cfg/ folder containing
## al make functions and configuration. You may edit everything and add new source files as required by your project.
##
## Command line options:
##    -h | --help                    - Shows help information on the terminal.
##

source ${GBT_PATH}/tools/libs/bash_library.sh
PROJECTDIR=
TEMPLATE_FOLDER=${GBT_PATH}/templates/prj

###############################################################
###############################################################
## Show how this script is to be used and exit
##
function usage() {
   echo "${COLOR_LIGHT_YELLOW}USAGE"
   echo "  ${COLOR_LIGHT_BLUE}$(basename $0) ${COLOR_LIGHT_CYAN}<project_folder_name> [options]"
   echo
   echo "${COLOR_CYAN}  This script creates a new folder and fills it up with required files to use that folder as a basic GBTelera project. \
Once the folder is created, you only have to launch 'make' command inside it to build the project an generate the GB file. \
A basic main.asm and header.asm source files are created under src/ sub-folder, and a standard cfg/ folder containing \
al make functions and configuration. You may edit everything and add new source files as required by your project."
   echo
   echo "${COLOR_LIGHT_YELLOW}OPTIONS"
   echo "${COLOR_LIGHT_BLUE}  -h | --help"
   echo "${COLOR_CYAN}       Shows this help information"
   echo ${COLOR_NORMAL}
   exit 1
}

###############################################################
###############################################################
## Check command line parameters
##

if (( $# < 1 )); then
   usage
fi

while (( $# >= 1 )); do
   case $1 in
      ## Show Help
      "-h" | "--help")
         usage
      ;;
      ## Get main parameter (ProjectDir)
      *)
         if isCommandLineOption "$1"; then
            paramError "Unrecognized command line option '$1'" 7
         elif ! isEmpty "$PROJECTDIR"; then
            paramError "Unrecognized parameter '$1'. Have you already provided a <project_folder> parameter?" 6
         elif [[ $1 =~ ^.*/.*$ ]]; then
            paramError "'$1' is not a valid name for your project folder. Project folder names must not contain slashes '/'." 7
         elif [ -e "$1" ]; then
            paramError "'$1' already exist in filesystem. Choose another name for your <project_folder>" 8
         fi
         PROJECTDIR="$1"
      ;;
   esac
   shift
done


###############################################################
###############################################################
## Some checks
##
if isEmpty "$PROJECTDIR"; then
   paramError "No name was given to create project main folder."
elif isFolderReadable "$PROJECTDIR"; then
   paramError "'$PROJECTDIR' already exists."
fi

###############################################################
###############################################################
## Create new project
##

# Welcome message
stageMessage "GBTelera" "Creating new project in ${COLOR_WHITE}${PROJECTDIR}/"
coloredMachineEcho "${COLOR_CYAN}" 0.005 "> Creating project folder..."
drawOK
coloredMachineEcho "${COLOR_CYAN}" 0.005 "> Duplicating scafolding basic project template..."
cp -rT "${TEMPLATE_FOLDER}" "${PROJECTDIR}"
drawOK
coloredMachineEcho "${COLOR_WHITE}" 0.005 "Project folder created and ready."
echo
